### ISSUE TITLE
Optional authentication

### ISSUE THREAD

**Issue by marttinen** [felixheck/hapi-auth-keycloak#13]
I'm trying to implement optional authentication using `mode: 'optional'`.

For it to work, the error response on unauthorized requests (e.g. without an authorization header) must return `boom.unauthorized(null, schema)`.

A quick search resulted in the regarding lines:
- https://github.com/felixheck/hapi-auth-keycloak/blob/master/src/index.js#L146
- https://github.com/felixheck/hapi-auth-keycloak/blob/master/src/utils.js#L119

Not sure what the best way to implement it is, looking at
`return boom.unauthorized(err ? err.message : msg, scheme, ...`

**Comment by felixheck** [comment]
Hi Max.

Happy you'd like to use the plugin even after I quit the company ;-)
Ehmm..good question. Never covered such use cases, thought hapi handles this internally w/o further actions inside the auth. 

So related to your comment it'd be enough to replace the `err ? err.message : msg` part with `null`?
Would be happy if you can try it..hopefully it works with the included `strategy` + `reason`. If so it'd be perfect if you just do the adjustments and adjust the relating tests. PR is welcome ;-) 

If you're not motivated to fire a PR, I'll tackle the issue saturday.

**Comment by marttinen** [comment]
Hey, exactly, or `err ? err.message : null` in there. Or, alternatively, implement a check if the header is set at all. I'm not sure what the best solution is here...

As reference: https://github.com/hapijs/discuss/issues/655

**Comment by felixheck** [comment]
When it’s possible to pass additional values like the reason etc, we could skip the first parameter and replace it with `null`. Because the reason already contains the error message :) 

I’d like to go with this solution.  

--

**edit:** please try branch https://github.com/felixheck/hapi-auth-keycloak/tree/3.3.0-rc

**Comment by felixheck** [comment]
And adjust the utility function as well. 
Additionally we could add the `error.message or msg` as another property called `error` to the object

**Comment by marttinen** [comment]
Hey, I've added some tests now now it seems like the authentication always succeeds when `mode: 'optional'`.

https://github.com/felixheck/hapi-auth-keycloak/pull/14

I'm try to get my head around this:
> When the scheme payload() method throws an error with a message, it means payload validation failed due to bad payload. If the error has no message but includes a scheme name (e.g. Boom.unauthorized(null, 'Custom')), authentication may still be successful if the route auth.payload configuration is set to 'optional'.

If I understand it correctly:
- on missing auth header: `boom.unauthorized(null, ...)`
- on invalid auth header: `boom.unauthorized(err.message, ...)`

I'll try to implement it in the PR later.

**Comment by felixheck** [comment]
Published as v3.3.0 — thanks a lot Max!

https://github.com/felixheck/hapi-auth-keycloak/releases/tag/v3.3.0
