### ISSUE TITLE
Unable to use 'publicKey' option to verify JWT in tests

### ISSUE THREAD

**Issue by sundeer** [felixheck/hapi-auth-keycloak#15]
In a live production environment my options look like this:
```
options: {
    realmUrl: 'https://mykeycloak.com/auth/realms/myrealm',
    clientId: 'myclientid',
}
```
... so the publicKey is pulled from my Keycloak server and cached on first use as I understand it. Is that right?

While writing some integration tests around authentication, I created a key-pair and corresponding valid JWT, then set the options like this:
```
options: {
    realmUrl: 'http://nonexistanturl.nonexistant',
    clientId: 'testclientid',
    publicKey: 'string representation of publicKey in PEM format'
}
```
running a test using the valid JWT I created, this is the response.result I'm getting:
```
{ 
    statusCode: 401,
    error: 'Unauthorized',
    message: 'Invalid credentials',
    attributes:
         {
             strategy: 'keycloak-jwt',
             reason: 'invalid token (wrong ISS)',
             error: 'Invalid credentials'
         } 
}
```
not what I expected. After some fiddling, the only way I could get this working was to set realmUrl to localhost
```
options: {
    realmUrl: 'http://localhost',
    clientId: 'testclientid',
    publicKey: 'string representation of publicKey in PEM format'
}
```
then the response.result is what I would expect with a valid JWT. NOTE - The 400 is from the graphql layer which tells me the JWT is valid.
```
{
     statusCode: 400,
     error: 'Bad Request',
     message: 'GET query missing.'
 }
```
shouldn't the presence of the 'publicKey' option override the realmUrl key?

**Comment by felixheck** [comment]
Hi, thanks for raising the issue.

> ... so the publicKey is pulled from my Keycloak server and cached on first use as I understand it. Is that right?

Yes, that's right.

> After some fiddling, the only way I could get this working was to set realmUrl to localhost

This is caused by the keycloak node library.
It's a security check and I didn't ignore it, because it seems right to me to be compliant with the keycloak security check. 

> shouldn't the presence of the 'publicKey' option override the realmUrl key?

Can you provide a concrete reason, why this should be the case?

Thanks.

**Comment by sundeer** [comment]
Thanks for the fast response and this excellent plugin.

I'm aware of keycloak's node lib (keycloak-connect) and read thru the documentation but saw nothing about the security check you mentioned. What is that?

So, my reasoning for thinking that 'publicKey' and 'realmUrl' would be mutually exclusive is that, in the case where 'publicKey' is provided, there's no need to query the server to fetch the public key because it already has it. I guess there's something deeper going on. I'll admit I have a about a C- level understanding of OIDC and OAuth.

**Comment by felixheck** [comment]
Happy to hear you like it :) 

It's part of the validation function the middleware provides:
https://github.com/keycloak/keycloak-nodejs-connect/blob/fe34e77864dab44f725c3fcee83834c4f9cddb0b/middleware/auth-utils/grant-manager.js#L331

It checks lots of fields to ensure that the token is valid.
It's really strict but I'd like to be compliant with the approach.

This function is the reason why it's currently necessary to add a realmUrl.
It's not for fetching (line >=359) but for validating the token (line 341).

If you'd like to get rid of this strict security check, feel free to provide a proposal.
But it should be optional, the plugin should be as secure as possible by default; thanks for your understanding :) 

Thanks

**Comment by sundeer** [comment]
I get it now. I need to mint my JWT with a proper ISS key to satisfy the security check.

AFA the efficacy of that ISS check goes, I'm no sec guru for sure, but, it does seem odd to use information from a thing as part of the validation of that same thing. 

I suppose it's like a cop, while looking at your ID, asking you if you know your own birthday. If you know it, you still may not be who you say you are, but if you don't, then it's, "Please step out of the car sir."

Thanks again for your help.

**Comment by felixheck** [comment]
Yep, that's correct :)
