### ISSUE TITLE
Offline signed token verification

### ISSUE THREAD

**Issue by mihaidma** [felixheck/hapi-auth-keycloak#16]
This code is calling validate token:
https://github.com/felixheck/hapi-auth-keycloak/blob/master/src/index.js#L33

But validate token has an extra parameter `expectedType`:
https://github.com/keycloak/keycloak-nodejs-connect/blob/master/middleware/auth-utils/grant-manager.js#L428
Because that field is undefined if the typ field from token is filled with anything the validation will fail.

I have in a token generated by Keycloak, in payload, the following content:
```
{
...
"typ": "Bearer",
...
}
```

So the comparison is made with `undefined`.
Looks to me that a `Bearer` string should be passed as param in the validate call from the hapi plugin.

What do you think? Is this a bug?

**Comment by felixheck** [comment]
Thanks @mihaidma for the bug report — it's definitely not intended.
The bug is caused by a [security fix](https://github.com/keycloak/keycloak-nodejs-connect/pull/146) — adding `'Bearer'` as expected type would fix this at a first glance.

**Comment by felixheck** [comment]
Published as `v3.4.0`

**Comment by mihaidma** [comment]
Thank you @felixheck, and also thank you for the work you do on plugin.
