### ISSUE TITLE
[featureRequest] Enable multi-tenant setup

### ISSUE THREAD

**Issue by youett** [felixheck/hapi-auth-keycloak#19]
Hey,
I was wondering if you ever considered extending this plugin to allow it to be reused for different client/realms?
My goal is to have different routes in my application being authenticated by different client/realms than other routes.
I think the only change one would need is to make the strategy name `keycloak-jwt` and maybe the decorator `kjwt` flexible through the options.
Best
Jonathan

**Comment by felixheck** [comment]
Hi @youett — thanks a lot for your issues and interest in this plugin! 😊 
To be honest, I haven't yet thought about it, just were quite unsure if I should assign a fixed name/decorator. That's obviously the reason why I shouldn't 😬

Would you mind contributing in the form of a PR?
Your guess with the necessary change seems to be 100% right — probably the bigger task will be to add tests covering all the edge cases (like don't overriding an existing `kjwt` decorator).

Please let me know what you think, would really love to see your contribution.
Thanks and have a nice weekend 👋

**Comment by youett** [comment]
Hey Felix,
I am a bit busy now but I will try to make a PR for you this week so you can review it.

**Comment by felixheck** [comment]
Thanks a lot, really appreciate your effort! 🙏  Looking forward to it.
